<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="wangmengleideMacBook-Pro.local" name="com.course.chapter5.TimeOutTest" tests="2" failures="0" timestamp="29 八月 2018 06:57:33 GMT" time="4.023" errors="1">
  <testcase name="TestSuccess" time="2.006" classname="com.course.chapter5.TimeOutTest"/>
  <testcase name="TestFailed" time="2.017" classname="com.course.chapter5.TimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.course.chapter5.TimeOutTest.TestFailed() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.course.chapter5.TimeOutTest.TestFailed() didn't finish within the time-out 2000
at java.util.concurrent.FutureTask.setException(FutureTask.java:251)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- TestFailed -->
</testsuite> <!-- com.course.chapter5.TimeOutTest -->
